repos:
  repo: local
  hooks:
    id: requerements
    name: requerements
    entry: bash -c 'venv/bin/pip3 freeze > requeriments.txt; git add . requeriments.txt'
    language: system
    pass_filenames: false
    stages: [commit]